=== AmpereComputing/panthera/src/ampere/python/panthera/cheetah/schema/specification.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:panthera:cheetah:specification",
    "title": "Cheetah Specification",
    "description": "A specification of configurations to run within Panthera sim",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "Name of configuration"
            },
            "exe": {
                "type": "string",
                "description": "Simulator executable"
            },
            "workloads": {
                "type": "string",
                "description": "Workloads path (otherwise uses default)"
            },
            "pre_sim": {
                "type": "array",
                "description": "Pre-commands",
                "items": {
                    "type": "array",
                    "items": {
                        "type": ["string", "array"]
                    }
                }
            },
            "sim_parameters": {
                "type": "array",
                "description": "Parameters to panthera sim",
                "items": {
                    "type": ["string", "array"]
                }
            },
            "parameters": {
                "type": "array",
                "description": "Parameters to simulator",
                "items": {
                    "type": ["string", "array"]
                }
            },
            "evp": {
                "type": "array",
                "description": "Parameters to evp (not including summarize)",
                "items": {
                    "type": ["string", "array"]
                }
            },
            "post_sim": {
                "type": "array",
                "description": "Post-commands",
                "items": {
                    "type": "array",
                    "items": {
                        "type": ["string", "array"]
                    }
                }
            }
        },
        "required": [
            "name"
        ]
    }
}

=== AmpereComputing/panthera/src/ampere/config/cheetah/json/rtl_snippets_domino_bpu_warmup.json
[
    {
        "name": "Panthera_ES_files",
        "exe": "{panthera_root}/bin/amperesys",
        "pre_sim": [
            [
                "{panthera_root}/bin/bobcat",
                "-bs", "{branchstream_path}",
                "-top.core.decoders", "[\"furiosa\"]",
                "-top.core:cfg", "{panthera_root}/config/model/core/connor/connor-tage.cfg",
                "-top.core.bpu.save_warmup_file", "{name}.bpu_warmup.json.gz"
            ]
        ],
        "evp": [
            "-i", "sys.soc_0.core_0.gpc.instruction_commit=100",
            "--start", "sys.soc_0.core_0.gpc.instruction_commit=10000",
            "--stop", "sys.soc_0.core_0.gpc.instruction_commit=30000",
            "--exit",
            "@base.cfg",
            "+capture", "{name}.es.xz"
        ],
        "parameters": [
            "-cfg", "{panthera_root}/config/model/sys/domino-core-rtl.cfg",
            "-sys.soc_0.core_0:append-cfg", "{panthera_root}/config/model/core/pv/base.cfg",
            "-event_stream_always", "true",
            "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
            "-sys.soc_0.core_0.l2c.warmup_ms", "{memstream_path}",
            "-sys.soc_0.core_0.speculative_memory_image", "true",
	    "-sys.soc_0.core_0.bpu.warmup_file", "{name}.bpu_warmup.json.gz",
            "-sys.soc_0.core_0.gpc.max_instructions", "30000"
        ],
        "post_sim": [
            [
                "{panthera_root}/bin/panthera", "events.tracing",
                "--compress",
                "--output", "{name}.json.gz",
                "@{panthera_root}/config/events.tracing/summary.cfg",
                "{name}.es.xz"
            ]
        ]
    }
]

=== AmpereComputing/panthera/src/ampere/config/cheetah/json/event_trace.json
[
    {
        "name": "domino",
        "exe": "{panthera_root}/bin/amperesys",
        "evp": [
            "-i", "sys.soc_0.core_0.gpc.instruction_commit=100",
            "--start", "sys.soc_0.core_0.gpc.instruction_commit=10000",
            "--stop", "sys.soc_0.core_0.gpc.instruction_commit=30000",
            "--exit",
            "@base.cfg",
            "+capture", "{name}.es.xz"
        ],
        "parameters": [
            "-cfg", "{panthera_root}/config/model/sys/domino.cfg",
            "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
            "-sys.soc_0.core_0.l2c.warmup_ms", "{memstream_path}",
            "-sys.soc_0.core_0.speculative_memory_image", "true",
            "-sys.soc_0.core_0.gpc.max_instructions", "30000"
        ],
        "post_sim": [
            [
                "{panthera_root}/bin/panthera", "events.tracing",
                "--compress",
                "--output", "{name}.json.gz",
                "@{panthera_root}/config/events.tracing/summary.cfg",
                "{name}.es.xz"
            ]
        ]
    }
]

=== AmpereComputing/panthera/src/ampere/config/cheetah/json/tigris_study.json
[
    {
        "name": "base",
        "exe": "{panthera_root}/bin/tigris",
        "parameters": [
            "-instruction_stream", "{workload_path}",
            "-memory_stream", "{memstream_path}",
            "-cfg", "{panthera_root}/config/model/core/prefetching/tigris/core.cfg",
            "-max_instructions", "10000000"
        ],
        "evp": [
            "-i", "top.instruction=30000", "@tigris.cfg"
        ]
    }
]

=== AmpereComputing/panthera/src/ampere/config/cheetah/json/rtl_snippets_micro.json
[
    {
        "name": "rtl_snippets",
        "exe": "{panthera_root}/bin/amperesys",
        "evp": [
            "-i", "sys.soc_0.core_0.gpc.instruction_commit=100",
            "--start", "sys.soc_0.core_0.gpc.instruction_commit=10000",
            "--stop", "sys.soc_0.core_0.gpc.instruction_commit=30000",
            "--exit",
            "@base.cfg",
            "+capture", "{name}.es"
        ],
        "parameters": [
            "-cfg", "{panthera_root}/config/model/sys/siryn.cfg",
            "-cfg", "{panthera_root}/config/model/sys/siryn-core-rtl.cfg",
            "-event_stream_always", "true",
            "-sys.soc_0.memory_[0-3]+.max_throughput", "128",
            "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
            "-sys.soc_0.core_0.speculative_memory_image", "true",
            "-sys.soc_0.core_0.gpc.max_instructions", "10000"
        ]
    }
]

=== AmpereComputing/panthera/src/ampere/config/cheetah/json/rtl_snippets_rogue_bpu_warmup.json
[
    {
        "name": "rtl_snippets",
        "exe": "{panthera_root}/bin/amperesys",
        "pre_sim": [
            [
                "{panthera_root}/bin/bobcat",
                "-bs", "{branchstream_path}",
                "-top.core.decoders", "[\"furiosa\"]",
                "-top.core:cfg", "{panthera_root}/config/model/core/trinity/trinity-tage.cfg",
                "-top.core.bpu.save_warmup_file", "{name}.bpu_warmup.json.gz"
            ]
        ],
        "evp": [
            "-i", "sys.soc_0.core_0.gpc.instruction_commit=100",
            "--start", "sys.soc_0.core_0.gpc.instruction_commit=10000",
            "--stop", "sys.soc_0.core_0.gpc.instruction_commit=30000",
            "--exit",
            "@base.cfg",
            "+capture", "{name}.es"
        ],
        "parameters": [
            "-cfg", "{panthera_root}/config/model/sys/rogue-core-rtl.cfg",
            "-event_stream_always", "true",
            "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
            "-sys.soc_0.core_0.l2c.warmup_ms", "{memstream_path}",
            "-sys.soc_0.core_0.speculative_memory_image", "true",
            "-sys.soc_0.core_0.bpu.warmup_file", "{name}.bpu_warmup.json.gz",
            "-sys.soc_0.core_0.gpc.max_instructions", "30000"
        ],
        "post_sim": [
            [
                "{panthera_root}/bin/panthera", "events.tracing",
                "--compress",
                "--output", "{name}.json.gz",
                "@{panthera_root}/config/events.tracing/summary.cfg",
                "{name}.es"
            ]
        ]
    }
]

=== AmpereComputing/panthera/src/ampere/config/cheetah/json/is_catus_study.json
[
    {
        "name": "catus",
        "exe": "{panthera_root}/bin/is_catus",
        "parameters": [
            "-instruction_stream", "{workload_path}",
            "-max_instructions", "10000000"
        ],
        "evp": [
            "-i", "top.instruction_commit=1000000",
            "+count", "-a"
        ]
    }
]

=== AmpereComputing/panthera/src/ampere/sys/test/sim_integration.json
[
  {
    "name": "sim_evp_start",
    "exe": "{panthera_root}/bin/amperesys",
    "parameters": [
        "-cfg", "{panthera_root}/config/model/sys/domino.cfg",
        "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
        "-sys.soc_0.core_0.gpc.max_instructions", "10000"
    ],
    "evp": [
        "-i", "*.gpc.instruction_commit=100",
        "--start", "*.gpc.instruction_commit=5000",
        "@base.cfg"
    ],
    "post_sim": [
        ["grep", "-q", "-E", ",50[01][0-9],", "{directory}/{name}.summary.csv"]
    ]
  },
  {
    "name": "sim_evp_start_end",
    "exe": "{panthera_root}/bin/amperesys",
    "parameters": [
        "-cfg", "{panthera_root}/config/model/sys/domino.cfg",
        "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
        "-sys.soc_0.core_0.gpc.max_instructions", "10000"
    ],
    "evp": [
        "-i", "*.gpc.instruction_commit=100",
        "--start", "*.gpc.instruction_commit=5000",
        "--stop", "*.gpc.instruction_commit=7500",
        "@base.cfg"
    ],
    "post_sim": [
        ["grep", "-q", ",2500,", "{directory}/{name}.summary.csv"]
    ]
  },
  {
    "name": "sim_evp_start_stop_exit",
    "exe": "{panthera_root}/bin/amperesys",
    "parameters": [
        "-cfg", "{panthera_root}/config/model/sys/domino.cfg",
        "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
        "-sys.soc_0.core_0.gpc.max_instructions", "10000"
    ],
    "evp": [
        "-i", "*.gpc.instruction_commit=100",
        "--start", "*.gpc.instruction_commit=5000",
        "--stop", "*.gpc.instruction_commit=7500",
        "--exit",
        "@base.cfg"
    ],
    "post_sim": [
        ["grep", "-q", "-E", "S\\w+g: exiting on stop", "{directory}/{name}.log"],
        ["grep", "-q", "-E", "S\\w+n complete: stopped by event stream processor", "{directory}/{name}.log"],
        ["grep", "-q", ",2500,", "{directory}/{name}.summary.csv"]
    ]
  },
  {
    "name": "sim_evp_capture_event_trace",
    "exe": "{panthera_root}/bin/amperesys",
    "parameters": [
        "-cfg", "{panthera_root}/config/model/sys/domino.cfg",
        "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
        "-sys.soc_0.core_0.gpc.max_instructions", "10000"
    ],
    "evp": [
        "-i", "*.gpc.instruction_commit=100",
        "@base.cfg", "+capture", "{directory}/{name}.es"
    ],
    "post_sim": [
        [
            "{panthera_root}/bin/panthera", "events.tracing",
            "--compress",
            "--output", "{directory}/{name}.json.gz",
            "@{panthera_root}/config/events.tracing/summary.cfg",
            "{directory}/{name}.es"
        ]
    ]
  },
  {
    "name": "sim_evp_start_stop_capture_event_trace",
    "exe": "{panthera_root}/bin/amperesys",
    "parameters": [
        "-cfg", "{panthera_root}/config/model/sys/domino.cfg",
        "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
        "-sys.soc_0.core_0.gpc.max_instructions", "10000"
    ],
    "evp": [
        "-i", "*.gpc.instruction_commit=100",
        "--start", "*.gpc.instruction_commit=5000",
        "--stop", "*.gpc.instruction_commit=7500",
        "@base.cfg", "+capture", "{directory}/{name}.es"
    ],
    "post_sim": [
        [
            "{panthera_root}/bin/panthera", "events.tracing",
            "--compress",
            "--output", "{directory}/{name}.json.gz",
            "@{panthera_root}/config/events.tracing/summary.cfg",
            "{directory}/{name}.es"
        ]
    ]
  }
]

=== AmpereComputing/panthera/src/ampere/config/cheetah/json/rtl_snippets_rogue.json
[
    {
        "name": "rtl_snippets",
        "exe": "{panthera_root}/bin/amperesys",
        "evp": [
            "-i", "sys.soc_0.core_0.gpc.instruction_commit=100",
            "--start", "sys.soc_0.core_0.gpc.instruction_commit=10000",
            "--stop", "sys.soc_0.core_0.gpc.instruction_commit=30000",
            "--exit",
            "@base.cfg",
            "+capture", "{name}.es"
        ],
        "parameters": [
            "-cfg", "{panthera_root}/config/model/sys/rogue-core-rtl.cfg",
            "-event_stream_always", "true",
            "-sys.soc_0.core_0.instruction_stream_name", "{workload_path}",
            "-sys.soc_0.core_0.l2c.warmup_ms", "{memstream_path}",
            "-sys.soc_0.core_0.speculative_memory_image", "true",
            "-sys.soc_0.core_0.gpc.max_instructions", "30000"
        ],
        "post_sim": [
            [
                "{panthera_root}/bin/panthera", "events.tracing",
                "--compress",
                "--output", "{name}.json.gz",
                "@{panthera_root}/config/events.tracing/summary.cfg",
                "{name}.es"
            ]
        ]
    }
]
