=== AmpereComputing/panthera/src/ampere/python/panthera/tracing/schema/workload.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:panthera:tracing:workload",
    "title": "Workloads",
    "description": "A specification of workloads and associated files/parameters",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "Trace name"
            },
            "file": {
                "type": "string",
                "description": "Instruction stream file (.is.xz)"
            },
            "workload": {
                "type": "string",
                "description": "Workload trace is a part of"
            },
            "suite": {
                "type": "string",
                "description": "Suite trace/workload is a part of"
            },
            "weight": {
                "type": "number",
                "description": "Trace weight (by instructions) within workload"
            },
            "pan_cache_preload_file": {
                "type": "string",
                "description": "Memory stream (.ms.xz) for cache preload"
            },
            "pan_branch_warmup_file": {
                "type": "string",
                "description": "Branch stream (.bs.xz) for branch-predictor warmup"
            },
            "warmup_instructions": {
                "type": "number",
                "description": "Amount of warmup instructions (before measurement) used when tracing"
            },
            "measurement_instructions": {
                "type": "number",
                "description": "Amount of instructions traced"
            },
            "cooldown_instructions": {
                "type": "number",
                "description": "Amount of cooldown instructions (after measurement) used when tracing"
            }
        },
        "required": [
            "name", "workload", "suite", "weight", "file"
        ]
    }
}

=== AmpereComputing/panthera/src/ampere/core/test/fast_regress_workloads.json
[
  {
    "name": "gcc",
    "file": "502.gcc-3.13171_chop.is.xz",
    "workload": "502.gcc",
    "suite": "SPEC2107int",
    "weight": 1.0
  },
  {
    "name": "mcf",
    "file": "505.mcf-1.59701_chop.is.xz",
    "workload": "505.mcf",
    "suite": "SPEC2107int",
    "weight": 1.0
  },
  {
    "name": "namd",
    "file": "508.namd-1.114894_chop.is.xz",
    "workload": "508.namd",
    "suite": "SPEC2107int",
    "weight": 1.0
  },
  {
    "name": "xalancbmk",
    "file": "523.xalancbmk-1.8395_chop.is.xz",
    "workload": "523.xalancbmk",
    "suite": "SPEC2107int",
    "weight": 1.0
  },
  {
    "name": "x264",
    "file": "525.x264-3.94854_chop.is.xz",
    "workload": "525.x264",
    "suite": "SPEC2107int",
    "weight": 1.0
  },
  {
    "name": "nab",
    "file": "544.nab-1.65277_chop.is.xz",
    "workload": "544.nab",
    "suite": "SPEC2107int",
    "weight": 1.0
  },
  {
    "name": "exchange2",
    "file": "548.exchange2-1.18342_chop.is.xz",
    "workload": "548.exchange2",
    "suite": "SPEC2107int",
    "weight": 1.0
  }
]

=== AmpereComputing/panthera/src/ampere/python/test/fixtures/tracelists/basic.json
[
    {
        "name": "1000.python_07",
        "file": "1000.python_07.is.xz",
        "weight": 1.0,
        "workload": "1000.python",
        "suite": "python"
    },
    {
        "name": "999.goodbye_23",
        "file": "999.goodbye_23.is.xz",
        "weight": 0.5,
        "workload": "999.goodbye",
        "suite": "goodbye"
    },
    {
        "name": "999.goodbye_7",
        "file": "999.goodbye_7.is.xz",
        "weight": 0.4,
        "workload": "999.goodbye",
        "suite": "goodbye"
    },
    {
        "name": "999.hello",
        "file": "999.hello.is.xz",
        "weight": 1.0,
        "workload": "999.hello",
        "suite": "hello"
    }
]
